name: my_coins
description: Create your coin collection and follow up your progress
publish_to: 'none'
version: 0.4.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.0
  collection: ^1.17.2
  equatable: ^2.0.5
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_storage: ^11.2.6
  firebase_ui_auth: ^1.6.5
  firebase_ui_localizations: ^1.5.3
  firebase_ui_oauth_google: ^1.2.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.2
  intl: any
  json_annotation: ^4.8.1
  photo_view: ^0.14.0
  sliver_tools: ^0.2.12
  uuid: ^3.0.7
  vector_graphics: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
  assets:
    - assets/svgs/