name: my_coins
description: Create your coin collection and follow up your progress
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: ^7.7.1
  cloud_firestore: ^4.8.4
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  firebase_ui_auth: ^1.6.2
  firebase_ui_localizations: ^1.5.0
  firebase_ui_oauth_google: ^1.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  intl: any
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf