// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9jUQvWnwon5se0LcnCBLFZwsA4sV0Yog',
    appId: '1:38384210019:android:eb6a5c493564d347972856',
    messagingSenderId: '38384210019',
    projectId: 'minhas-moedas-app',
    storageBucket: 'minhas-moedas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9SFT6veWAmLMhbgz4C8S9lGqH8W3Z2Ik',
    appId: '1:38384210019:ios:33c73452ccf8d9f0972856',
    messagingSenderId: '38384210019',
    projectId: 'minhas-moedas-app',
    storageBucket: 'minhas-moedas-app.appspot.com',
    androidClientId: '38384210019-lqj9t5urabqr0o60211744tjgfs01lh9.apps.googleusercontent.com',
    iosClientId: '38384210019-4sd6o1hpot7d5nksd58trgkmabuh988j.apps.googleusercontent.com',
    iosBundleId: 'br.eng.pedromendes.myCoins',
  );
}
